[project]
name = "mqttdemo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "paho-mqtt>=2.1.0",
    "pyside6>=6.9.1",
]
